-- Add token field to users table for admin authentication
-- This script adds a token field to store JWT tokens for admin users

-- Add token field to users table (if it doesn't exist)
ALTER TABLE users ADD COLUMN IF NOT EXISTS token TEXT;

-- Create index for token field for better performance (if it doesn't exist)
CREATE INDEX IF NOT EXISTS idx_users_token ON users(token);

-- Update admin user with a valid JWT token
-- Note: Replace with an actual JWT token generated by your authentication system
UPDATE users 
SET token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AcGV0cm9kZWFsaHViLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNTEyOTk1NCwiZXhwIjoxNzM1NzM0NzU0fQ.sample_token_signature_for_admin'
WHERE email = 'admin@petrodealhub.com' AND role = 'admin';

-- If admin user doesn't exist, create one
INSERT INTO users (email, password, firstName, lastName, role, token, createdAt, updatedAt)
SELECT 
    'admin@petrodealhub.com',
    '$2b$10$TKh8H1.PfQx37YgCzwiKb.N2XvZ5vdVkG5o5R.5J5J5v5v5v5v5v5v', -- hashed 'admin123'
    'Admin',
    'User',
    'admin',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AcGV0cm9kZWFsaHViLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczNTEyOTk1NCwiZXhwIjoxNzM1NzM0NzU0fQ.sample_token_signature_for_admin',
    NOW(),
    NOW()
WHERE NOT EXISTS (
    SELECT 1 FROM users WHERE email = 'admin@petrodealhub.com'
);

-- Display the updated admin user to verify the token was added
SELECT id, email, role, token, created_at FROM users WHERE email = 'admin@petrodealhub.com';