-- Example: Adding Port of Hamburg to the database
INSERT INTO ports (
  name, country, region, city, lat, lng, timezone,
  type, status, classification, capacity, annual_throughput,
  max_vessel_length, max_vessel_beam, max_draught, channel_depth,
  berth_count, total_berth_length, port_authority, operator,
  operating_hours, pilotage_required, tug_assistance,
  rail_connections, road_connections, airport_distance,
  warehouse_area, storage_capacity, security_level,
  customs_facilities, quarantine_facilities, safety_record,
  available_services, cargo_types, currency, average_handling_cost,
  address, email, phone, website, description
) VALUES (
  'Port of Hamburg',
  'Germany',
  'Europe',
  'Hamburg',
  '53.5472',
  '9.9680',
  'CET',
  'Commercial',
  'Operational',
  'International',
  8000000,
  130000000,
  '400m',
  '59m',
  '15.5m',
  '17m',
  300,
  '43000m',
  'Hamburg Port Authority',
  'HHLA Hamburg Hafen und Logistik AG',
  '24/7',
  true,
  true,
  true,
  true,
  '8km',
  '500000 sqm',
  '5000000 tons',
  'ISPS Level 1',
  true,
  true,
  'Very Good',
  'Container handling, Ro-Ro, Break bulk, Storage, Rail connections',
  'Containers, General Cargo, Bulk, Ro-Ro',
  'EUR',
  '€120/TEU',
  'Bei St. Annen 1, 20457 Hamburg, Germany',
  'info@hamburg-port.de',
  '+49 40 4288-0',
  'https://www.hamburg-port.de',
  'Gateway to the world - Germany''s largest seaport and third-largest in Europe'
);

-- Example: Adding Port of Jebel Ali to the database  
INSERT INTO ports (
  name, country, region, city, lat, lng, timezone,
  type, status, classification, capacity, annual_throughput,
  max_vessel_length, max_vessel_beam, max_draught, channel_depth,
  berth_count, total_berth_length, port_authority, operator,
  operating_hours, pilotage_required, tug_assistance,
  rail_connections, road_connections, airport_distance,
  warehouse_area, storage_capacity, security_level,
  customs_facilities, quarantine_facilities, safety_record,
  available_services, cargo_types, currency, average_handling_cost,
  address, email, phone, website, description
) VALUES (
  'Jebel Ali Port',
  'United Arab Emirates',
  'Middle East',
  'Dubai',
  '24.9917',
  '55.0369',
  'GST',
  'Commercial',
  'Operational',
  'International',
  15000000,
  22000000,
  '450m',
  '65m',
  '18m',
  '20m',
  134,
  '25000m',
  'Dubai Ports Authority',
  'DP World',
  '24/7',
  true,
  true,
  true,
  true,
  '35km',
  '800000 sqm',
  '12000000 tons',
  'ISPS Level 1',
  true,
  true,
  'Excellent',
  'Container handling, Cruise terminal, Free zone, Logistics',
  'Containers, General Cargo, Cruise, Oil & Gas',
  'AED',
  '$180/TEU',
  'Jebel Ali Free Zone, Dubai, UAE',
  'info@dpworld.ae',
  '+971 4 881 5000',
  'https://www.dpworld.ae',
  'Largest man-made harbor and busiest port in the Middle East'
);