-- SQL script to import oil shipping companies
-- First, clear existing companies
DELETE FROM companies;

-- Insert oil shipping companies
INSERT INTO companies (name, country, region, description, specialization, status)
VALUES
('Maersk Tankers', 'Denmark', 'Europe', 'Maersk Tankers is a leading oil shipping company based in Denmark. The company operates a fleet of modern vessels specializing in crude oil and petroleum products transportation. They are a key player in the global maritime oil transportation industry.', 'Oil Shipping', 'active'),
('Frontline Ltd.', 'Bermuda', 'North America', 'Frontline Ltd. is one of the world''s largest tanker shipping companies, with a fleet specializing in the transportation of crude oil and refined petroleum products. Based in Bermuda, it operates on all major shipping routes worldwide.', 'Oil Shipping', 'active'),
('Euronav', 'Belgium', 'Europe', 'Euronav is a Belgian tanker company and one of the largest crude oil shipping companies in the world. The company operates a fleet of modern, high-quality vessels dedicated to the maritime transportation of crude oil.', 'Oil Shipping', 'active'),
('Teekay Corporation', 'Canada', 'North America', 'Teekay Corporation is a Canadian shipping company specializing in crude oil and LNG transportation. With a global presence, Teekay provides marine services to the world''s leading oil and gas companies.', 'Oil Shipping', 'active'),
('Nordic American Tankers', 'Bermuda', 'North America', 'Nordic American Tankers is a Bermuda-based tanker company focusing on the transportation of crude oil. The company specializes in operating Suezmax tankers, which are versatile vessels that can navigate through the Suez Canal.', 'Oil Shipping', 'active'),
('DHT Holdings', 'Bermuda', 'North America', 'DHT Holdings is a crude oil tanker company headquartered in Bermuda. The company owns and operates a fleet of modern crude oil tankers that transport petroleum products around the globe, serving major international oil companies.', 'Oil Shipping', 'active'),
('Scorpio Tankers', 'Monaco', 'Europe', 'Scorpio Tankers is one of the world''s largest product tanker companies, based in Monaco. The company specializes in the transportation of refined petroleum products and operates a young, eco-friendly fleet.', 'Oil Shipping', 'active'),
('Tsakos Energy Navigation', 'Greece', 'Europe', 'Tsakos Energy Navigation is a Greek shipping company focusing on the transportation of crude oil, petroleum products, and LNG. With decades of experience, the company maintains high safety and operational standards.', 'Oil Shipping', 'active'),
('Bahri', 'Saudi Arabia', 'Middle East', 'Bahri, also known as the National Shipping Company of Saudi Arabia, is a global leader in logistics and transportation. The company is a major player in crude oil transportation and owns one of the largest VLCC fleets in the world.', 'Oil Shipping', 'active'),
('COSCO Shipping Energy', 'China', 'Asia-Pacific', 'COSCO Shipping Energy Transportation is a subsidiary of China COSCO Shipping Corporation Limited. The company focuses on oil and gas transportation, operating a large fleet of tankers that transport crude oil and refined products globally.', 'Oil Shipping', 'active'),
('Sovcomflot', 'Russia', 'Europe', 'Sovcomflot is Russia''s largest shipping company and one of the world''s leading energy shipping companies. The company specializes in the transportation of crude oil, petroleum products, and liquefied gas, particularly in harsh climate conditions.', 'Oil Shipping', 'active'),
('Mitsui O.S.K. Lines', 'Japan', 'Asia-Pacific', 'Mitsui O.S.K. Lines (MOL) is one of Japan''s largest shipping companies. Within its diversified fleet, the company operates oil tankers that transport crude oil and petroleum products worldwide, with a strong focus on safety and environmental performance.', 'Oil Shipping', 'active'),
('China Merchants Energy Shipping', 'China', 'Asia-Pacific', 'China Merchants Energy Shipping is a Chinese shipping company specializing in oil and gas transportation. The company operates a modern fleet of VLCCs and other tankers, supporting China''s energy security and global trade.', 'Oil Shipping', 'active'),
('Knutsen NYK Offshore Tankers', 'Norway', 'Europe', 'Knutsen NYK Offshore Tankers is a joint venture between the Norwegian Knutsen Group and Japanese NYK. The company specializes in shuttle tankers that transport crude oil from offshore oil fields to onshore terminals and refineries.', 'Oil Shipping', 'active'),
('Odfjell', 'Norway', 'Europe', 'Odfjell is a Norwegian shipping company specializing in the transportation of chemicals, acids, edible oils, and clean petroleum products. The company operates a global fleet of sophisticated chemical tankers.', 'Oil Shipping', 'active'),
('Stena Bulk', 'Sweden', 'Europe', 'Stena Bulk is a Swedish shipping company that transports crude oil, petroleum products, and gas worldwide. Known for innovation, the company operates a modern, fuel-efficient fleet with a focus on environmental sustainability.', 'Oil Shipping', 'active'),
('Navios Maritime Acquisition', 'Monaco', 'Europe', 'Navios Maritime Acquisition is a tanker company based in Monaco. The company owns and operates a fleet of modern tankers for the transportation of petroleum products and bulk liquid chemicals.', 'Oil Shipping', 'active'),
('International Seaways', 'USA', 'North America', 'International Seaways is one of the largest tanker companies worldwide, providing energy transportation services for crude oil and petroleum products. Based in the USA, the company operates a diverse fleet of tankers.', 'Oil Shipping', 'active'),
('Hafnia', 'Singapore', 'Asia-Pacific', 'Hafnia is one of the world''s leading product tanker owners and operators, based in Singapore. The company specializes in the transportation of refined oil products, with a modern and fuel-efficient fleet.', 'Oil Shipping', 'active'),
('Okeanis Eco Tankers', 'Greece', 'Europe', 'Okeanis Eco Tankers is a Greek tanker company focused on the transportation of crude oil. The company operates a young, eco-friendly fleet of tankers designed to reduce environmental impact while maximizing operational efficiency.', 'Oil Shipping', 'active'),
('Diamond S Shipping', 'USA', 'North America', 'Diamond S Shipping is an American shipping company specializing in the seaborne transportation of crude oil and refined petroleum products. The company operates a large fleet of modern vessels serving customers worldwide.', 'Oil Shipping', 'active'),
('AET Tankers', 'Singapore', 'Asia-Pacific', 'AET Tankers is a leading owner and operator of petroleum tankers based in Singapore. The company specializes in the global transportation of crude oil, clean petroleum products, and chemicals, with a strong focus on sustainability.', 'Oil Shipping', 'active'),
('Ocean Tankers', 'Singapore', 'Asia-Pacific', 'Ocean Tankers is a Singapore-based shipping company specializing in the transportation of petroleum products. The company operates a diverse fleet of tankers ranging from coastal vessels to large crude carriers.', 'Oil Shipping', 'active'),
('Kuwait Oil Tanker Company', 'Kuwait', 'Middle East', 'Kuwait Oil Tanker Company (KOTC) is responsible for the transportation of Kuwait''s oil exports. The company operates a fleet of modern tankers that transport crude oil, liquefied petroleum gas, and refined petroleum products.', 'Oil Shipping', 'active'),
('Thenamaris', 'Greece', 'Europe', 'Thenamaris is a Greek ship management company that manages a diverse fleet including crude oil tankers, product tankers, and LNG carriers. The company is known for its high operational standards and commitment to quality shipping.', 'Oil Shipping', 'active');