import { InsertRefinery } from "@shared/schema";
import { REGIONS, REFINERY_STATUSES } from "@shared/constants";
import { ACCURATE_REFINERIES, getAccurateRefineries } from "./refineryCoordinates";

// Type for refineries with numeric lat/lng
type RefinerySource = {
  name: string;
  country: string;
  region: string;
  lat: number;
  lng: number;
  capacity: number;
  status: string;
};

// Global refineries dataset
const WORLD_REFINERIES: RefinerySource[] = [
  // North America Refineries
  {
    name: "Texas Gulf Coast Refinery",
    country: "United States",
    region: "north-america",
    lat: 29.7604,
    lng: -95.3698,
    capacity: 607000,
    status: "operational",
  },
  {
    name: "Louisiana Refining Complex",
    country: "United States",
    region: "north-america",
    lat: 30.2241,
    lng: -91.3547,
    capacity: 540000,
    status: "operational",
  },
  {
    name: "Baytown Refinery",
    country: "United States",
    region: "north-america",
    lat: 29.7544,
    lng: -94.9811,
    capacity: 584000,
    status: "operational",
  },
  {
    name: "Whiting Refinery",
    country: "United States",
    region: "north-america",
    lat: 41.6636,
    lng: -87.4898,
    capacity: 435000,
    status: "operational",
  },
  {
    name: "Port Arthur Refinery",
    country: "United States",
    region: "north-america",
    lat: 29.8957,
    lng: -93.9852,
    capacity: 603000,
    status: "operational",
  },
  {
    name: "Pascagoula Refinery",
    country: "United States",
    region: "north-america",
    lat: 30.3658,
    lng: -88.5561,
    capacity: 330000,
    status: "operational",
  },
  {
    name: "Montreal Refinery",
    country: "Canada",
    region: "north-america",
    lat: 45.5017,
    lng: -73.5673,
    capacity: 137000,
    status: "operational",
  },
  {
    name: "Edmonton Refinery",
    country: "Canada",
    region: "north-america",
    lat: 53.5461,
    lng: -113.4938,
    capacity: 191500,
    status: "operational",
  },
  {
    name: "Sarnia Refinery",
    country: "Canada",
    region: "north-america",
    lat: 42.9774,
    lng: -82.4065,
    capacity: 120000,
    status: "operational",
  },
  {
    name: "Deer Park Refinery",
    country: "United States",
    region: "north-america",
    lat: 29.7051,
    lng: -95.1183,
    capacity: 340000,
    status: "maintenance",
  },

  // South America Refineries
  {
    name: "Paulinia Refinery (REPLAN)",
    country: "Brazil",
    region: "south-america",
    lat: -22.7286,
    lng: -47.1486,
    capacity: 415500,
    status: "operational",
  },
  {
    name: "Cartagena Refinery",
    country: "Colombia",
    region: "south-america",
    lat: 10.3910,
    lng: -75.4794,
    capacity: 165000,
    status: "operational",
  },
  {
    name: "Amuay Refinery",
    country: "Venezuela",
    region: "south-america",
    lat: 11.7500,
    lng: -70.2167,
    capacity: 640000,
    status: "maintenance",
  },
  {
    name: "Cardón Refinery",
    country: "Venezuela",
    region: "south-america",
    lat: 11.6667,
    lng: -70.2333,
    capacity: 310000,
    status: "maintenance",
  },
  {
    name: "Talara Refinery",
    country: "Peru",
    region: "south-america",
    lat: -4.5794,
    lng: -81.2759,
    capacity: 65000,
    status: "operational",
  },
  {
    name: "Luján de Cuyo Refinery",
    country: "Argentina",
    region: "south-america",
    lat: -32.8869,
    lng: -68.8486,
    capacity: 106000,
    status: "operational",
  },
  {
    name: "La Plata Refinery",
    country: "Argentina",
    region: "south-america",
    lat: -34.8526,
    lng: -57.9535,
    capacity: 189000,
    status: "operational",
  },

  // Central America Refineries
  {
    name: "Salina Cruz Refinery",
    country: "Mexico",
    region: "central-america",
    lat: 16.1811,
    lng: -95.1961,
    capacity: 330000,
    status: "operational",
  },
  {
    name: "Tula Refinery",
    country: "Mexico",
    region: "central-america",
    lat: 20.0467,
    lng: -99.3411,
    capacity: 315000,
    status: "operational",
  },
  {
    name: "Cadereyta Refinery",
    country: "Mexico",
    region: "central-america",
    lat: 25.5936,
    lng: -99.9892,
    capacity: 275000,
    status: "operational",
  },
  {
    name: "Minatitlán Refinery",
    country: "Mexico",
    region: "central-america",
    lat: 17.9742,
    lng: -94.5536,
    capacity: 250000,
    status: "maintenance",
  },
  {
    name: "Limón Refinery",
    country: "Costa Rica",
    region: "central-america",
    lat: 9.9911,
    lng: -83.0546,
    capacity: 25000,
    status: "offline",
  },

  // Western Europe Refineries
  {
    name: "Rotterdam Refinery",
    country: "Netherlands",
    region: "western-europe",
    lat: 51.9225,
    lng: 4.4792,
    capacity: 404000,
    status: "operational",
  },
  {
    name: "Pernis Refinery",
    country: "Netherlands",
    region: "western-europe",
    lat: 51.8852,
    lng: 4.3860,
    capacity: 416000,
    status: "operational",
  },
  {
    name: "Antwerp Refinery",
    country: "Belgium",
    region: "western-europe",
    lat: 51.2477,
    lng: 4.4207,
    capacity: 413500,
    status: "operational",
  },
  {
    name: "Fos-sur-Mer Refinery",
    country: "France",
    region: "western-europe",
    lat: 43.4528,
    lng: 4.9297,
    capacity: 210000,
    status: "operational",
  },
  {
    name: "Gelsenkirchen Refinery",
    country: "Germany",
    region: "western-europe",
    lat: 51.5204,
    lng: 7.0794,
    capacity: 265000,
    status: "operational",
  },
  {
    name: "Schwedt Refinery",
    country: "Germany",
    region: "western-europe",
    lat: 53.0605,
    lng: 14.3201,
    capacity: 240000,
    status: "operational",
  },
  {
    name: "Karlsruhe Refinery",
    country: "Germany",
    region: "western-europe",
    lat: 49.0069,
    lng: 8.4037,
    capacity: 310000,
    status: "operational",
  },
  {
    name: "Grangemouth Refinery",
    country: "United Kingdom",
    region: "western-europe",
    lat: 56.0197,
    lng: -3.7200,
    capacity: 210000,
    status: "maintenance",
  },
  {
    name: "Immingham Refinery",
    country: "United Kingdom",
    region: "western-europe",
    lat: 53.6338,
    lng: -0.2181,
    capacity: 221000,
    status: "operational",
  },
  {
    name: "Mongstad Refinery",
    country: "Norway",
    region: "western-europe",
    lat: 60.8122,
    lng: 5.0205,
    capacity: 226000,
    status: "operational",
  },
  {
    name: "Slagen Refinery",
    country: "Norway",
    region: "western-europe",
    lat: 59.1900,
    lng: 10.2585,
    capacity: 110000,
    status: "operational",
  },
  {
    name: "Preemraff Lysekil",
    country: "Sweden",
    region: "western-europe",
    lat: 58.2733,
    lng: 11.4376,
    capacity: 220000,
    status: "operational",
  },
  {
    name: "Milazzo Refinery",
    country: "Italy",
    region: "western-europe",
    lat: 38.1781,
    lng: 15.2442,
    capacity: 243000,
    status: "operational",
  },
  {
    name: "Tarragona Refinery",
    country: "Spain",
    region: "western-europe",
    lat: 41.1188,
    lng: 1.2489,
    capacity: 190000,
    status: "operational",
  },
  {
    name: "Bilbao Refinery",
    country: "Spain",
    region: "western-europe",
    lat: 43.2627,
    lng: -2.9253,
    capacity: 220000,
    status: "operational",
  },
  {
    name: "Sines Refinery",
    country: "Portugal",
    region: "western-europe",
    lat: 37.9571,
    lng: -8.8699,
    capacity: 220000,
    status: "operational",
  },

  // Eastern Europe Refineries
  {
    name: "Plock Refinery",
    country: "Poland",
    region: "eastern-europe",
    lat: 52.5500,
    lng: 19.7058,
    capacity: 327000,
    status: "operational",
  },
  {
    name: "Gdansk Refinery",
    country: "Poland",
    region: "eastern-europe",
    lat: 54.3520,
    lng: 18.6466,
    capacity: 210000,
    status: "operational",
  },
  {
    name: "Bratislava Refinery",
    country: "Slovakia",
    region: "eastern-europe",
    lat: 48.1486,
    lng: 17.1077,
    capacity: 124000,
    status: "operational",
  },
  {
    name: "Burgas Refinery",
    country: "Bulgaria",
    region: "eastern-europe",
    lat: 42.5048,
    lng: 27.4626,
    capacity: 190000,
    status: "operational",
  },
  {
    name: "Kralupy Refinery",
    country: "Czech Republic",
    region: "eastern-europe",
    lat: 50.2411,
    lng: 14.3101,
    capacity: 84000,
    status: "operational",
  },
  {
    name: "Litvinov Refinery",
    country: "Czech Republic",
    region: "eastern-europe",
    lat: 50.5331,
    lng: 13.6119,
    capacity: 110000,
    status: "operational",
  },
  {
    name: "Danube Refinery",
    country: "Hungary",
    region: "eastern-europe",
    lat: 47.3100,
    lng: 18.8764,
    capacity: 165000,
    status: "operational",
  },
  {
    name: "Mozyr Refinery",
    country: "Belarus",
    region: "eastern-europe",
    lat: 52.0495,
    lng: 29.1832,
    capacity: 240000,
    status: "maintenance",
  },

  // Middle East Refineries
  {
    name: "Jamnagar Refinery",
    country: "India",
    region: "middle-east",
    lat: 22.2806,
    lng: 69.8789,
    capacity: 1240000,
    status: "operational",
  },
  {
    name: "Ras Tanura Refinery",
    country: "Saudi Arabia",
    region: "middle-east",
    lat: 26.6444,
    lng: 50.1642,
    capacity: 550000,
    status: "operational",
  },
  {
    name: "Ruwais Refinery",
    country: "United Arab Emirates",
    region: "middle-east",
    lat: 24.1175,
    lng: 52.7300,
    capacity: 817000,
    status: "operational",
  },
  {
    name: "Abadan Refinery",
    country: "Iran",
    region: "middle-east",
    lat: 30.3392,
    lng: 48.2809,
    capacity: 400000,
    status: "operational",
  },
  {
    name: "Mina Al-Ahmadi Refinery",
    country: "Kuwait",
    region: "middle-east",
    lat: 29.0758,
    lng: 48.1302,
    capacity: 466000,
    status: "operational",
  },
  {
    name: "Basra Refinery",
    country: "Iraq",
    region: "middle-east",
    lat: 30.5000,
    lng: 47.7833,
    capacity: 140000,
    status: "maintenance",
  },
  {
    name: "Yanbu Refinery",
    country: "Saudi Arabia",
    region: "middle-east",
    lat: 24.0889,
    lng: 38.0639,
    capacity: 400000,
    status: "operational",
  },
  {
    name: "Sitra Refinery",
    country: "Bahrain",
    region: "middle-east",
    lat: 26.1544,
    lng: 50.6544,
    capacity: 260000,
    status: "operational",
  },
  {
    name: "Mesaieed Refinery",
    country: "Qatar",
    region: "middle-east",
    lat: 24.9873,
    lng: 51.5497,
    capacity: 283000,
    status: "operational",
  },
  {
    name: "Sohar Refinery",
    country: "Oman",
    region: "middle-east",
    lat: 24.4700,
    lng: 56.6428,
    capacity: 116000,
    status: "operational",
  },

  // North Africa Refineries
  {
    name: "Skikda Refinery",
    country: "Algeria",
    region: "north-africa",
    lat: 36.8764,
    lng: 6.9061,
    capacity: 335000,
    status: "operational",
  },
  {
    name: "Zawiya Refinery",
    country: "Libya",
    region: "north-africa",
    lat: 32.7505,
    lng: 12.7281,
    capacity: 120000,
    status: "maintenance",
  },
  {
    name: "Ras Lanuf Refinery",
    country: "Libya",
    region: "north-africa",
    lat: 30.5000,
    lng: 18.5333,
    capacity: 220000,
    status: "offline",
  },
  {
    name: "Alexandria Refinery",
    country: "Egypt",
    region: "north-africa",
    lat: 31.2001,
    lng: 29.9187,
    capacity: 100000,
    status: "operational",
  },
  {
    name: "Mohammedia Refinery",
    country: "Morocco",
    region: "north-africa",
    lat: 33.6835,
    lng: -7.3857,
    capacity: 155000,
    status: "operational",
  },
  {
    name: "Bizerte Refinery",
    country: "Tunisia",
    region: "north-africa",
    lat: 37.2744,
    lng: 9.8739,
    capacity: 32000,
    status: "operational",
  },

  // Southern Africa Refineries
  {
    name: "Sapref Refinery",
    country: "South Africa",
    region: "southern-africa",
    lat: -29.9087,
    lng: 30.9726,
    capacity: 180000,
    status: "operational",
  },
  {
    name: "Enref Refinery",
    country: "South Africa",
    region: "southern-africa",
    lat: -29.8579,
    lng: 31.0292,
    capacity: 135000,
    status: "operational",
  },
  {
    name: "Cape Town Refinery",
    country: "South Africa",
    region: "southern-africa",
    lat: -33.9249,
    lng: 18.4241,
    capacity: 100000,
    status: "maintenance",
  },
  {
    name: "Luanda Refinery",
    country: "Angola",
    region: "southern-africa",
    lat: -8.8368,
    lng: 13.2343,
    capacity: 65000,
    status: "operational",
  },
  {
    name: "Ndola Refinery",
    country: "Zambia",
    region: "southern-africa",
    lat: -12.9987,
    lng: 28.6487,
    capacity: 34000,
    status: "maintenance",
  },
  {
    name: "Dar es Salaam Refinery",
    country: "Tanzania",
    region: "southern-africa",
    lat: -6.8126,
    lng: 39.2982,
    capacity: 15000,
    status: "offline",
  },
  {
    name: "Mombasa Refinery",
    country: "Kenya",
    region: "southern-africa",
    lat: -4.0435,
    lng: 39.6682,
    capacity: 90000,
    status: "offline",
  },

  // Russia Refineries
  {
    name: "Omsk Refinery",
    country: "Russia",
    region: "russia",
    lat: 54.9924,
    lng: 73.3686,
    capacity: 500000,
    status: "operational",
  },
  {
    name: "Kirishi Refinery",
    country: "Russia",
    region: "russia",
    lat: 59.4751,
    lng: 32.0246,
    capacity: 340000,
    status: "operational",
  },
  {
    name: "Moscow Refinery",
    country: "Russia",
    region: "russia",
    lat: 55.7558,
    lng: 37.6173,
    capacity: 360000,
    status: "operational",
  },
  {
    name: "Ryazan Refinery",
    country: "Russia",
    region: "russia",
    lat: 54.6269,
    lng: 39.6966,
    capacity: 340000,
    status: "operational",
  },
  {
    name: "Yaroslavl Refinery",
    country: "Russia",
    region: "russia",
    lat: 57.6261,
    lng: 39.8845,
    capacity: 300000,
    status: "operational",
  },
  {
    name: "Nizhnekamsk Refinery",
    country: "Russia",
    region: "russia",
    lat: 55.6359,
    lng: 51.8139,
    capacity: 360000,
    status: "operational",
  },
  {
    name: "Perm Refinery",
    country: "Russia",
    region: "russia",
    lat: 58.0105,
    lng: 56.2502,
    capacity: 300000,
    status: "maintenance",
  },
  {
    name: "Volgograd Refinery",
    country: "Russia",
    region: "russia",
    lat: 48.7080,
    lng: 44.5133,
    capacity: 290000,
    status: "operational",
  },
  {
    name: "Ufa Refinery Complex",
    country: "Russia",
    region: "russia",
    lat: 54.7430,
    lng: 55.9678,
    capacity: 450000,
    status: "operational",
  },

  // China Refineries
  {
    name: "Zhenhai Refinery",
    country: "China",
    region: "china",
    lat: 29.9490,
    lng: 121.7390,
    capacity: 460000,
    status: "operational",
  },
  {
    name: "Maoming Refinery",
    country: "China",
    region: "china",
    lat: 21.6618,
    lng: 110.9206,
    capacity: 360000,
    status: "operational",
  },
  {
    name: "Dalian Refinery",
    country: "China",
    region: "china",
    lat: 38.9140,
    lng: 121.6147,
    capacity: 410000,
    status: "operational",
  },
  {
    name: "Tianjin Refinery",
    country: "China",
    region: "china",
    lat: 39.0842,
    lng: 117.2009,
    capacity: 320000,
    status: "operational",
  },
  {
    name: "Shanghai Refinery",
    country: "China",
    region: "china",
    lat: 31.2304,
    lng: 121.4737,
    capacity: 320000,
    status: "operational",
  },
  {
    name: "Guangzhou Refinery",
    country: "China",
    region: "china",
    lat: 23.1291,
    lng: 113.2644,
    capacity: 270000,
    status: "operational",
  },
  {
    name: "Fujian Refinery",
    country: "China",
    region: "china",
    lat: 26.0715,
    lng: 119.2948,
    capacity: 280000,
    status: "operational",
  },
  {
    name: "Qingdao Refinery",
    country: "China",
    region: "china",
    lat: 36.0671,
    lng: 120.3826,
    capacity: 216000,
    status: "operational",
  },
  {
    name: "Huizhou Refinery",
    country: "China",
    region: "china",
    lat: 23.0292,
    lng: 114.3899,
    capacity: 240000,
    status: "operational",
  },
  {
    name: "Wuhan Refinery",
    country: "China",
    region: "china",
    lat: 30.5928,
    lng: 114.3055,
    capacity: 170000,
    status: "maintenance",
  },

  // Asia-Pacific Refineries
  {
    name: "Ulsan Refinery",
    country: "South Korea",
    region: "asia-pacific",
    lat: 35.5384,
    lng: 129.3114,
    capacity: 840000,
    status: "operational",
  },
  {
    name: "Yeosu Refinery",
    country: "South Korea",
    region: "asia-pacific",
    lat: 34.7604,
    lng: 127.6622,
    capacity: 785000,
    status: "operational",
  },
  {
    name: "Negishi Refinery",
    country: "Japan",
    region: "asia-pacific",
    lat: 35.4437,
    lng: 139.6380,
    capacity: 270000,
    status: "operational",
  },
  {
    name: "Chiba Refinery",
    country: "Japan",
    region: "asia-pacific",
    lat: 35.6062,
    lng: 140.1063,
    capacity: 190000,
    status: "operational",
  },
  {
    name: "Kawasaki Refinery",
    country: "Japan",
    region: "asia-pacific",
    lat: 35.5310,
    lng: 139.7070,
    capacity: 235000,
    status: "operational",
  },
  {
    name: "Sakai Refinery",
    country: "Japan",
    region: "asia-pacific",
    lat: 34.5730,
    lng: 135.4555,
    capacity: 200000,
    status: "operational",
  },
  {
    name: "Mizushima Refinery",
    country: "Japan",
    region: "asia-pacific",
    lat: 34.5030,
    lng: 133.7717,
    capacity: 300000,
    status: "operational",
  },
  {
    name: "Daesan Refinery",
    country: "South Korea",
    region: "asia-pacific",
    lat: 36.9380,
    lng: 126.4327,
    capacity: 305000,
    status: "operational",
  },
  {
    name: "Onsan Refinery",
    country: "South Korea",
    region: "asia-pacific",
    lat: 35.4362,
    lng: 129.3595,
    capacity: 669000,
    status: "operational",
  },

  // Southeast Asia/Oceania Refineries
  {
    name: "Singapore Refinery",
    country: "Singapore",
    region: "southeast-asia-oceania",
    lat: 1.2655,
    lng: 103.8077,
    capacity: 592000,
    status: "operational",
  },
  {
    name: "ExxonMobil Singapore",
    country: "Singapore",
    region: "southeast-asia-oceania",
    lat: 1.2700,
    lng: 103.7998,
    capacity: 605000,
    status: "operational",
  },
  {
    name: "Melaka Refinery",
    country: "Malaysia",
    region: "southeast-asia-oceania",
    lat: 2.1896,
    lng: 102.2501,
    capacity: 270000,
    status: "operational",
  },
  {
    name: "Port Dickson Refinery",
    country: "Malaysia",
    region: "southeast-asia-oceania",
    lat: 2.5290,
    lng: 101.7963,
    capacity: 155000,
    status: "operational",
  },
  {
    name: "Bataan Refinery",
    country: "Philippines",
    region: "southeast-asia-oceania",
    lat: 14.5995,
    lng: 120.5414,
    capacity: 180000,
    status: "maintenance",
  },
  {
    name: "Map Ta Phut Refinery",
    country: "Thailand",
    region: "southeast-asia-oceania",
    lat: 12.6748,
    lng: 101.1581,
    capacity: 215000,
    status: "operational",
  },
  {
    name: "Sriracha Refinery",
    country: "Thailand",
    region: "southeast-asia-oceania",
    lat: 13.1247,
    lng: 100.9207,
    capacity: 275000,
    status: "operational",
  },
  {
    name: "Balikpapan Refinery",
    country: "Indonesia",
    region: "southeast-asia-oceania",
    lat: -1.2379,
    lng: 116.8529,
    capacity: 260000,
    status: "operational",
  },
  {
    name: "Cilacap Refinery",
    country: "Indonesia",
    region: "southeast-asia-oceania",
    lat: -7.7420,
    lng: 109.0083,
    capacity: 348000,
    status: "operational",
  },
  {
    name: "Geelong Refinery",
    country: "Australia",
    region: "southeast-asia-oceania",
    lat: -38.0946,
    lng: 144.3613,
    capacity: 120000,
    status: "operational",
  },
  {
    name: "Marsden Point Refinery",
    country: "New Zealand",
    region: "southeast-asia-oceania",
    lat: -35.8372,
    lng: 174.4885,
    capacity: 135000,
    status: "operational",
  }
];

/**
 * Generate a large dataset of refineries for the application
 * @returns Array of refinery data ready to be inserted
 */
export function generateRefineryDataset(): InsertRefinery[] {
  // Use accurate refinery data from refineryCoordinates.ts
  return getAccurateRefineries().map(refinery => ({
    ...refinery,
    // Additional fields
    description: `${refinery.name} is a major oil refinery located in ${refinery.country}. It has a capacity of ${Number(refinery.capacity).toLocaleString()} barrels per day.`,
  }));
}

/**
 * Generate a random subset of refineries for testing
 * @param count Number of refineries to generate
 * @returns Array of refinery data
 */
export function generateRandomRefineries(count: number = 20): InsertRefinery[] {
  // Shuffle the array of refineries
  const shuffled = [...WORLD_REFINERIES].sort(() => 0.5 - Math.random());
  
  // Take the first 'count' elements
  return shuffled.slice(0, Math.min(count, WORLD_REFINERIES.length)).map(refinery => ({
    name: refinery.name,
    country: refinery.country,
    region: refinery.region,
    // Convert numbers to strings for lat/lng since database expects decimal type
    lat: String(refinery.lat),
    lng: String(refinery.lng),
    capacity: refinery.capacity,
    status: refinery.status,
    // Additional fields
    description: `${refinery.name} is a major oil refinery located in ${refinery.country}. It has a capacity of ${refinery.capacity.toLocaleString()} barrels per day.`,
  }));
}