export interface Database {
  public: {
    Tables: {
      vessels: {
        Row: {
          id: number;
          name: string;
          mmsi: string;
          imo: string;
          vesselType: string;
          flag: string;
          built: number | null;
          deadweight: number | null;
          length: string | null;
          width: string | null;
          status: string | null;
          currentLat: string | null;
          currentLng: string | null;
          destinationPort: string | null;
          departurePort: string | null;
          eta: string | null;
          speed: string | null;
          course: string | null;
          draught: string | null;
          cargoType: string | null;
          cargoCapacity: number | null;
          lastUpdated: string | null;
          metadata: string | null;
          createdAt: string | null;
          updatedAt: string | null;
          oilType: string | null;
          quantity: string | null;
          dealValue: string | null;
          price: string | null;
          marketPrice: string | null;
          routeDistance: string | null;
          departureDate: string | null;
          arrivalDate: string | null;
          destinationLat: string | null;
          destinationLng: string | null;
          departureLat: string | null;
          departureLng: string | null;
          averageSpeed: string | null;
          maxSpeed: string | null;
          fuelConsumption: string | null;
          emissionsCO2: string | null;
          lastPortVisited: string | null;
          nextPort: string | null;
          voyageNumber: string | null;
          charterer: string | null;
          operator: string | null;
          owner: string | null;
          imoClass: string | null;
          callSign: string | null;
          homePort: string | null;
          yearBuilt: number | null;
          grossTonnage: number | null;
        };
        Insert: Omit<Database['public']['Tables']['vessels']['Row'], 'id' | 'createdAt' | 'updatedAt'>;
        Update: Partial<Database['public']['Tables']['vessels']['Insert']>;
      };
      ports: {
        Row: {
          id: number;
          name: string;
          country: string;
          region: string;
          city: string | null;
          capacity: number | null;
          lat: string;
          lng: string;
          type: string | null;
          status: string | null;
          description: string | null;
          annualThroughput: number | null;
          maxVesselLength: string | null;
          maxVesselBeam: string | null;
          maxDraught: string | null;
          berthsAvailable: number | null;
          channelDepth: string | null;
          tidalRange: string | null;
          portAuthority: string | null;
          contactEmail: string | null;
          contactPhone: string | null;
          website: string | null;
          operatingHours: string | null;
          restrictions: string | null;
          facilities: string | null;
          services: string | null;
          ispsLevel: number | null;
          customsAvailable: boolean | null;
          quarantineAvailable: boolean | null;
          pilotageRequired: boolean | null;
          railConnection: boolean | null;
          roadConnection: boolean | null;
          airportDistance: string | null;
          storageCapacity: string | null;
          cargoTypes: string | null;
          waitTime: string | null;
          currency: string | null;
          charges: string | null;
          lastInspection: string | null;
          nextInspection: string | null;
          certifications: string | null;
          environmentalRating: string | null;
          safetyRating: string | null;
          operator: string | null;
          owner: string | null;
          timeZone: string | null;
          weatherConditions: string | null;
          tideInfo: string | null;
          navigationHazards: string | null;
          emergencyServices: string | null;
          repairFacilities: string | null;
          fuelAvailable: boolean | null;
          provisionsAvailable: boolean | null;
          wasteDisposal: boolean | null;
          createdAt: string | null;
        };
        Insert: Omit<Database['public']['Tables']['ports']['Row'], 'id' | 'createdAt'>;
        Update: Partial<Database['public']['Tables']['ports']['Insert']>;
      };
      refineries: {
        Row: {
          id: number;
          name: string;
          country: string;
          region: string;
          city: string | null;
          capacity: number | null;
          lat: string;
          lng: string;
          type: string | null;
          status: string | null;
          description: string | null;
          distillationCapacity: number | null;
          conversionCapacity: number | null;
          hydrogenCapacity: number | null;
          sulfurRecovery: number | null;
          processingUnits: string | null;
          storageCapacity: number | null;
          investmentCost: string | null;
          operatingCosts: string | null;
          revenue: string | null;
          profitMargin: string | null;
          marketShare: string | null;
          environmentalCertifications: string | null;
          safetyRecord: string | null;
          workforceSize: number | null;
          annualThroughput: number | null;
          crudeOilSources: string | null;
          pipelineConnections: string | null;
          shippingTerminals: string | null;
          railConnections: string | null;
          nearestPort: string | null;
          owner: string | null;
          operator: string | null;
          contactInfo: string | null;
          emergencyContacts: string | null;
          operationalStatus: string | null;
          mainProducts: string | null;
          specializations: string | null;
          certifications: string | null;
          lastInspection: string | null;
          nextInspection: string | null;
          createdAt: string | null;
        };
        Insert: Omit<Database['public']['Tables']['refineries']['Row'], 'id' | 'createdAt'>;
        Update: Partial<Database['public']['Tables']['refineries']['Insert']>;
      };
      users: {
        Row: {
          id: number;
          email: string;
          password: string;
          role: string;
          firstName: string | null;
          lastName: string | null;
          createdAt: string | null;
          updatedAt: string | null;
          token: string | null;
          stripeCustomerId: string | null;
          subscriptionStatus: string | null;
          subscriptionPlan: string | null;
          trialEndsAt: string | null;
          subscriptionStartedAt: string | null;
          subscriptionEndsAt: string | null;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'createdAt' | 'updatedAt'>;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
    };
  };
}