// Sample company data for oil shipping companies

export const oilCompanies = [
  {
    id: 1,
    name: "Saudi Aramco",
    country: "Saudi Arabia",
    region: "Middle East",
    headquarters: "Dhahran, Saudi Arabia",
    foundedYear: 1933,
    ceo: "Amin H. Nasser",
    fleetSize: 92,
    specialization: "Crude Oil & LNG",
    website: "https://www.aramco.com",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Saudi_Aramco_logo.svg/1200px-Saudi_Aramco_logo.svg.png",
    description: "Saudi Aramco is one of the world's largest integrated energy and chemicals companies, operating in multiple global markets. With a vast fleet of oil tankers and strategic partnerships, Aramco maintains a dominant position in the global oil shipping market. The company is known for its reliability in supply chain management and commitment to environmental sustainability in maritime operations.",
    revenue: 6200, // in millions
    employees: 70000,
    publiclyTraded: true,
    stockSymbol: "ARAMCO",
    status: "active",
  },
  {
    id: 2,
    name: "Abu Dhabi National Oil Company",
    country: "United Arab Emirates",
    region: "Middle East",
    headquarters: "Abu Dhabi, UAE",
    foundedYear: 1971,
    ceo: "Sultan Ahmed Al Jaber",
    fleetSize: 28,
    specialization: "Crude Oil & Petroleum Products",
    website: "https://www.adnoc.ae",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/ADNOC_logo.svg/1200px-ADNOC_logo.svg.png",
    description: "ADNOC is a leading diversified energy and petrochemicals group wholly owned by the Emirate of Abu Dhabi. The company's shipping division manages a significant fleet that transports crude oil and refined products across global markets, with particular emphasis on Asian destinations. ADNOC has invested heavily in expanding its maritime capacity and implementing advanced technologies for operational efficiency.",
    revenue: 1850,
    employees: 55000,
    publiclyTraded: false,
    status: "active",
  },
  {
    id: 3,
    name: "Kuwait Petroleum Corporation",
    country: "Kuwait",
    region: "Middle East",
    headquarters: "Kuwait City, Kuwait",
    foundedYear: 1980,
    ceo: "Hashem Sayed Hashem",
    fleetSize: 32,
    specialization: "Crude Oil & Refined Products",
    website: "https://www.kpc.com.kw",
    description: "Kuwait Petroleum Corporation (KPC) is Kuwait's national oil company, responsible for all state oil and gas operations. Through its subsidiary Kuwait Oil Tanker Company (KOTC), KPC operates a substantial fleet of oil tankers, LPG carriers, and product carriers. The company prides itself on maintaining high standards in maritime safety and environmental protection across its shipping operations.",
    revenue: 1100,
    employees: 22000,
    publiclyTraded: false,
    status: "active",
  },
  {
    id: 4,
    name: "Shell Global",
    country: "Netherlands",
    region: "Western Europe",
    headquarters: "The Hague, Netherlands",
    foundedYear: 1907,
    ceo: "Wael Sawan",
    fleetSize: 40,
    specialization: "Diversified Oil & Gas",
    website: "https://www.shell.com",
    logo: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Shell_logo.svg/1200px-Shell_logo.svg.png",
    description: "Royal Dutch Shell is a multinational oil and gas company with operations in more than 70 countries. Shell Shipping & Maritime manages one of the largest fleets of liquefied natural gas (LNG) carriers and oil tankers in the world. The company is at the forefront of implementing digital technologies and alternative fuels to reduce the carbon footprint of maritime transportation.",
    revenue: 3800,
    employees: 82000,
    publiclyTraded: true,
    stockSymbol: "SHEL",
    status: "active",
  },
  {
    id: 5,
    name: "ExxonMobil",
    country: "United States",
    region: "North America",
    headquarters: "Irving, Texas, USA",
    foundedYear: 1870,
    ceo: "Darren Woods",
    fleetSize: 35,
    specialization: "Crude Oil & Natural Gas",
    website: "https://www.exxonmobil.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/ExxonMobil_logo.svg/1200px-ExxonMobil_logo.svg.png",
    description: "ExxonMobil is one of the world's largest publicly traded energy providers and chemical manufacturers. The company's marine division operates a substantial fleet for transporting crude oil, petroleum products, and LNG around the globe. ExxonMobil has been instrumental in developing technical innovations for improved vessel efficiency and environmental performance in maritime shipping.",
    revenue: 4100,
    employees: 63000,
    publiclyTraded: true,
    stockSymbol: "XOM",
    status: "active",
  },
  {
    id: 6,
    name: "BP",
    country: "United Kingdom",
    region: "Western Europe",
    headquarters: "London, UK",
    foundedYear: 1909,
    ceo: "Bernard Looney",
    fleetSize: 38,
    specialization: "Integrated Oil & Gas",
    website: "https://www.bp.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/BP_logo.svg/1200px-BP_logo.svg.png",
    description: "BP is a global energy company with operations in Europe, North and South America, Australasia, Asia, and Africa. BP Shipping operates a diverse fleet of vessels including oil tankers, LNG carriers, and product carriers. The company has been a pioneer in implementing environmental management systems in its maritime operations and is committed to reducing greenhouse gas emissions from its shipping activities.",
    revenue: 2900,
    employees: 70100,
    publiclyTraded: true,
    stockSymbol: "BP",
    status: "active",
  },
  {
    id: 7,
    name: "Total Energies",
    country: "France",
    region: "Western Europe",
    headquarters: "Paris, France",
    foundedYear: 1924,
    ceo: "Patrick Pouyanné",
    fleetSize: 45,
    specialization: "Multi-Energy",
    website: "https://www.totalenergies.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/TotalEnergies_logo.svg/1200px-TotalEnergies_logo.svg.png",
    description: "TotalEnergies is a broad energy company that produces and markets fuels, natural gas, and electricity. The company's shipping division operates a significant fleet including LNG carriers, oil tankers, and bulk carriers. TotalEnergies is actively engaged in researching and deploying low-carbon solutions for maritime transportation, including biofuels and LNG as marine fuels.",
    revenue: 2450,
    employees: 105000,
    publiclyTraded: true,
    stockSymbol: "TTE",
    status: "active",
  },
  {
    id: 8,
    name: "Petrobras",
    country: "Brazil",
    region: "South America",
    headquarters: "Rio de Janeiro, Brazil",
    foundedYear: 1953,
    ceo: "Jean Paul Prates",
    fleetSize: 50,
    specialization: "Deepwater Oil Production & Transport",
    website: "https://www.petrobras.com.br",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Petrobras_logo_2019.svg/1200px-Petrobras_logo_2019.svg.png",
    description: "Petrobras is Brazil's state-controlled oil company and one of the largest oil producers in the world. The company's transportation subsidiary, Transpetro, operates a substantial fleet of oil tankers, product carriers, and support vessels. Petrobras has pioneered innovations in deep-water oil extraction and transportation, developing specialized vessels for offshore logistics.",
    revenue: 1800,
    employees: 45000,
    publiclyTraded: true,
    stockSymbol: "PBR",
    status: "active",
  },
  {
    id: 9,
    name: "Sinopec Corp",
    country: "China",
    region: "East Asia",
    headquarters: "Beijing, China",
    foundedYear: 1998,
    ceo: "Ma Yongsheng",
    fleetSize: 75,
    specialization: "Petroleum & Petrochemical Products",
    website: "https://www.sinopecgroup.com",
    description: "Sinopec Corp is one of China's largest petroleum and petrochemical enterprises. The company's shipping division manages an extensive fleet that transports crude oil and refined products across global markets, with particular focus on securing China's energy supply chains. Sinopec has invested significantly in expanding its maritime capabilities and upgrading its fleet with more environmentally friendly vessels.",
    revenue: 3550,
    employees: 384000,
    publiclyTraded: true,
    stockSymbol: "SNP",
    status: "active",
  },
  {
    id: 10,
    name: "Qatar Energy",
    country: "Qatar",
    region: "Middle East",
    headquarters: "Doha, Qatar",
    foundedYear: 1974,
    ceo: "Saad Sherida Al-Kaabi",
    fleetSize: 67,
    specialization: "LNG & Natural Gas Liquids",
    website: "https://www.qatarenergy.qa",
    description: "Qatar Energy (formerly Qatar Petroleum) is a state-owned petroleum company of Qatar. Through its subsidiary Nakilat, the company operates the world's largest fleet of liquefied natural gas (LNG) carriers. Qatar Energy has been instrumental in developing Qatar's position as the world's leading LNG exporter, with its maritime operations forming a critical link in the global LNG supply chain.",
    revenue: 2100,
    employees: 31000,
    publiclyTraded: false,
    status: "active",
  }
];